# Generated by Django 4.2 on 2023-05-12 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_rename_business_businessregistration_keyword'),
        ('websitepost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_post', to='business.businessregistration'),
        ),
        migrations.AddField(
            model_name='post',
            name='schedule_time',
            field=models.DateTimeField(null=True),
        ),
    ]
