# Generated by Django 4.2 on 2023-04-27 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.TextField(blank=True, null=True)),
                ('file_path', models.TextField(blank=True, null=True)),
                ('cdn_link', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BusinessRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('category', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True, null=True)),
                ('street_name', models.CharField(max_length=255)),
                ('city_zip', models.CharField(max_length=255)),
                ('city1', models.CharField(max_length=255)),
                ('city2', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('business_description', models.TextField()),
                ('business_days_and_hours', models.TextField()),
                ('images', models.ManyToManyField(related_name='BusinessImages', to='business.businessimage')),
            ],
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(max_length=255)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='business.businessregistration')),
            ],
        ),
    ]
