# Generated by Django 4.2 on 2023-05-02 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_alter_businessregistration_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessregistration',
            name='category',
        ),
    ]
