# Generated by Django 4.2 on 2023-05-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_remove_businessregistration_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessregistration',
            name='category',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
