# Generated by Django 4.2 on 2023-05-04 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_alter_businessregistration_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keywords',
            name='business',
        ),
        migrations.AddField(
            model_name='businessregistration',
            name='business',
            field=models.ManyToManyField(related_name='businesskeywords', to='business.keywords'),
        ),
        migrations.CreateModel(
            name='BusinessHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=3)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('closed', models.BooleanField(default=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_hours', to='business.businessregistration')),
            ],
        ),
    ]
