# Generated by Django 4.2 on 2023-05-04 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_remove_keywords_business_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessregistration',
            old_name='business',
            new_name='keyword',
        ),
    ]
